Salesfactory/gpt-rag-frontend

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/components/FeedbackRating/FeedbackRating.module.css
- frontend/src/components/FeedbackRating/FeedbackRating.tsx
- frontend/src/components/FeedbackRating/FeedbackRatingButton.module.css
- frontend/src/components/FeedbackRating/FeedbackRatingButton.tsx
- frontend/src/components/HistoryPannel/ChatHistoryListItem.tsx
- frontend/src/pages/chat/Chat.tsx
- frontend/src/pages/layout/Layout.tsx
- frontend/src/providers/AppProviders.tsx
in order for this to work, we need to add the key "orchestrator-host--feedback" and its corresponding function value to azure vault
> Sfc 76 77 78 feedback

- frontend/src/pages/chat/Chat.tsx
Reverts Salesfactory/gpt-rag-frontend#24
> Revert "SFC-90 Conversation History Sources are not opening in the side panel"

- frontend/src/pages/chat/Chat.tsx
Reverts Salesfactory/gpt-rag-frontend#23
> Revert "SFC-90 Conversation History - Sources are not opening in the side panel"

- backend/app.py
NEW ENVIRONMENT VARs =  
AZURE_STORAGE_CONNECTION_STRING
AZURE_CSV_STORAGE_CONTAINER
> SFC-312 create function to upload files to azure blob storage

- frontend/src/providers/AppProviders.tsx
& updated feedback shortcut
list of shortcuts:
Ctrl + Alt + 0(cero) Logout
Ctrl + Alt + 7 Subscription
Ctrl + Alt + 8 Feedback
Ctrl + Alt + 9 Account Admin
Ctrl + Alt + y New Chat
Ctrl + Alt + . History
Ctrl + Alt + , Settings
Ctrl + Alt + o Clear Chat
> SFC-143 add subscription shortcut

- frontend/src/components/PaymentGateway/ButtonPaymentGateway.tsx
- frontend/src/components/PaymentGateway/PaymentGateway.tsx
> SFC-352 add admin validation & redirect

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/components/PaymentGateway/PaymentGateway.tsx
Merging this PR to include the new subscription tiers
> FA-36-Update-the-UI-to-include-the-new-subscription-tiers

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/pages/admin/Admin.tsx
- frontend/vite.config.ts
[FA-40](https://salesfactoryai.atlassian.net/browse/FA-40)
The function to verify the subscription to the financial agent was added and bugs were fixed.
> Upgrade Subscription feature added

- backend/stripeTestLiveApiValidation.py
[FA-95](https://salesfactoryai.atlassian.net/browse/FA-95)
Configured a recurring Financial Assistant product in Stripe and built code that validates that the test and live products were set up correctly to fulfill the requirements of the project.
> Fa 95 create financial agent product on stripe for test and live environments

- frontend/src/api/api.ts
- frontend/src/pages/chat/Chat.tsx
> FA send user data in chat request

- backend/app.py
- frontend/src/api/api.ts
[FA-98](https://salesfactoryai.atlassian.net/browse/FA-98)
Added endpoints and added removeFinancialAssistant function to api.ts
> FA-98 Create an endpoint to delete the financial asistant subscription

- backend/app.py
- frontend/src/App.tsx
- frontend/src/api/api.ts
- frontend/src/components/SideMenu/SideMenu.tsx
- frontend/src/pages/financialassistant/FinancialAssistant.module.css
- frontend/src/pages/financialassistant/FinancialAssistant.tsx
[FA-164](https://salesfactoryai.atlassian.net/browse/FA-164)
[Update the user interface to include an option that allows users to subscribe to the financial assistant feature]
> Fa 164 update the user interface to include an option that allows users to subscribe to the financial assistant feature

- frontend/src/components/SideMenu/SideMenu.module.css
- frontend/src/components/Sidebar/Sidebar.module.css
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItem.tsx
[FA-193](https://salesfactoryai.atlassian.net/browse/FA-193)
[Align Sidebar Styling with Design Specifications]
> Implement the new UI menu

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/components/SettingsPanel/index.tsx
[FA-192](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-192)
[The functionality for the Navbar was added to the new UI]
> FA-192 Implement expected behavior in the navbar UI 

- backend/app.py
[FA-185](https://salesfactoryai.atlassian.net/browse/FA-185)
merging this code will allow you to fetch the subscription tiers for a particular subscription based on its subscription ID.
> Fa 185 create endpoint for getting subscriptions tiers by subscription id

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/components/Navbar/Navbar.module.css
[FA-177](https://salesfactoryai.atlassian.net/browse/FA-177)
[The Financial Assistant toggle has been estetically implemented]
> FA-177 Add the toggle for chatting with the financial-assistant

- backend/app.py
- frontend/src/App.tsx
- frontend/src/components/Navbar/Navbar.module.css
- frontend/src/components/Sidebar/Sidebar.module.css
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItem.tsx
- frontend/src/components/Sidebar/SidebarItemTypes.ts
- frontend/src/components/Sidebar/SidebarSectionTypes.ts
- frontend/src/providers/AppProviders.tsx
- frontend/src/router/ProtectedRoute.tsx
- frontend/vite.config.ts
…ol at sidebar lever
[FA-185](https://salesfactoryai.atlassian.net/browse/FA-185)
> FA-185 implement role base access control at sidebar level

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/providers/AppProviders.tsx
[FA-29](https://salesfactoryai.atlassian.net/browse/FA-29)
[Added the main function for the financial assistant toggle. Minor fixes to the Profile Card interaction with different elements of the navbar]
> Activate Financial Analyst Mode in Chat Interface

- .github/workflows/azure-dev.yml
add continuos deployment pipeline
> add a github actions deploy workflow

- .github/workflows/azure-dev.yml
[FA-206](https://salesfactoryai.atlassian.net/browse/FA-206)
> FA-209 Fix github action

- .github/workflows/azure-dev.yml
[FA-206](https://salesfactoryai.atlassian.net/browse/FA-206)
> FA 206 install zip in GitHub actions

- .github/workflows/azure-dev.yml
> FA-206 install zip on Github actions

- frontend/src/pages/admin/Admin.tsx
[FA-144](https://salesfactoryai.atlassian.net/browse/FA-114)
[Add Delete Icon Functionality]
> FA-144 Add Delete Icon Functionality

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/components/Navbar/Navbar.module.css
[FA-214](https://salesfactoryai.atlassian.net/browse/FA-214)
[Added navbar responsiveness to dimension changes (especially mobile devices) and FA toggle responsiveness]
> FA 214 - Responsiveness of the Navbar

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/components/Sidebar/Sidebar.module.css
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/pages/invitations/Invitations.tsx
[FA-220](https://salesfactoryai.atlassian.net/browse/FA-220)
[Fix the scrollbar and issues in the side bar]
> Fix the scrollbar and issues in the side bar

- frontend/src/App.tsx
- frontend/src/pages/logout/Logout.tsx
[FA-219](https://salesfactoryai.atlassian.net/browse/FA-219)
[Implemented the Route element so the button doesn't interfere with the endpoint]
> FA-219 Fix the logout button

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItem.tsx
[FA-224](https://salesfactoryai.atlassian.net/browse/FA-224)
[Fix the Sidebar Submenu when the user clicks on it]
> FA-224 Fix Sidebar Premium Features Submenu

- frontend/src/components/FeedbackRating/FeedbackRating.module.css
- frontend/src/components/FeedbackRating/FeedbackRating.tsx
- frontend/src/components/HistoryPannel/ChatHistoryPanel.tsx
- frontend/src/components/HistoryPannel/ChatHistoryPannel.module.css
- frontend/src/components/SettingsPanel/SettingsModal.module.css
- frontend/src/components/SettingsPanel/index.tsx
- frontend/src/pages/chat/Chat.module.css
- frontend/src/pages/chat/Chat.tsx
[FA-215](https://salesfactoryai.atlassian.net/browse/FA-215)
[Fix the Navbar Items and more issues with the panels]
> FA-215 Display navbar items as modals on mobile

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/components/Sidebar/Sidebar.module.css
[FA-230](https://salesfactoryai.atlassian.net/browse/FA-230)
[Added CSS Scrollbar and change the handler to be interactive with the elements of the Navbar]
> FA-230 Fix Sidebar Scrollbar desktop design and interaction with navbar elements

- frontend/src/components/Sidebar/Sidebar.tsx
[FA-231](https://salesfactoryai.atlassian.net/browse/FA-231)
[Added Basic, Custom and Admin tiers in the Admin Features]
> FA-231 The creator of an organization should automatically be assigned as the admin

- frontend/src/components/QuestionInput/QuestionInput.module.css
- frontend/src/components/QuestionInput/QuestionInput.tsx
- frontend/src/components/StartNewChatButton/StartNewChatButton.module.css
- frontend/src/components/StartNewChatButton/StartNewChatButton.tsx
- frontend/src/pages/chat/Chat.module.css
- frontend/src/pages/chat/Chat.tsx
[FA-225](https://salesfactoryai.atlassian.net/browse/FA-225)
[Updated UI/UX of the chat message box]
> FA-225 Updated chat box UI

- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/Answer/Answer.tsx
- frontend/src/components/UserChatMessage/UserChatMessage.module.css
- frontend/src/pages/chat/Chat.module.css
[FA-226](https://salesfactoryai.atlassian.net/browse/FA-226)
[Updated font sizes for desktop & mobile]
> FA-226 improve chat answers & questions

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/StartNewChatButton/StartNewChatButton.tsx
[FA-233](https://salesfactoryai.atlassian.net/browse/FA-233)
[Small update. Just an icon change]
> FA-233 Change the icon for Ai Chat and New Chat button to make it more intuitive for the user

- frontend/src/components/Sidebar/Sidebar.tsx
[FA-193](https://salesfactoryai.atlassian.net/browse/FA-193)
[Fix issues with side menu when non-admin user was showing extra division that was not needed]
> FA-193 Fix issues with the sidemenu

- frontend/src/components/FeedbackRating/FeedbackRating.module.css
- frontend/src/components/FeedbackRating/FeedbackRating.tsx
- frontend/src/components/HistoryPannel/ChatHistoryListItem.tsx
[FA-192](https://salesfactoryai.atlassian.net/browse/FA-192)
[Minor fixes]
> FA 192 Implement expected behavior in the navbar UI

- frontend/src/components/QuestionInput/QuestionInput.tsx
[FA-243](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-243)
[Minor changes. Just commenting the button]
> FA-243 Temporally removing the voice recognition button

- frontend/src/components/HistoryPannel/ChatHistoryPannel.module.css
- frontend/src/components/SettingsPanel/SettingsModal.module.css
- frontend/src/components/SettingsPanel/index.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
[FA-242](https://salesfactoryai.atlassian.net/browse/FA-242)
[Fix with chat history width ]
> Fa 242 chat history overlaps chat messages

- .github/workflows/azure-dev.yml
> HOTFIX inspect environments vars at deploy

- .github/workflows/azure-dev.yml
- .github/workflows/azure-prod.yml
> Hotfix inspect enviroments vars at deploy

- .github/workflows/azure-prod.yml
> FA-205 set up deployment prod (#183)

- .github/workflows/azure-prod.yml
> HOTFIX-set-PROD-credentials

- frontend/src/providers/AppProviders.tsx
[FA-251](https://salesfactoryai.atlassian.net/browse/FA-251)
[Added the variables in the AppProviders]
> FA-251 Capture Document Name and Agent Type from URL parameters

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/components/QuestionInput/QuestionInput.tsx
- frontend/src/pages/chat/Chat.tsx
[FA-252](https://salesfactoryai.atlassian.net/browse/FA-252)
[Send Chat Requests to Financial Agent Endpoint]
> FA-252 Send Chat Requests to Financial Agent Endpoint

- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/pages/chat/Chat.tsx
> HOTFIX include  document into financial agents request

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/pages/chat/Chat.tsx
> HOTFIX set key-vault for financial agent and send agent into chat payload

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/components/QuestionInput/QuestionInput.tsx
- frontend/src/pages/chat/Chat.tsx
- frontend/src/providers/AppProviders.tsx
> Release 0.1.1

- frontend/src/pages/reports/DistributionLists.module.css
- frontend/src/pages/reports/DistributionLists.tsx
- frontend/src/pages/reports/ReportManagement.module.css
- frontend/src/pages/reports/ReportManagement.tsx
- frontend/src/pages/resources/UploadResources.module.css
- frontend/src/pages/resources/UploadResources.tsx
- frontend/src/pages/studies/RequestStudies.module.css
- frontend/src/pages/studies/RequestStudies.tsx
[FA-244](https://salesfactoryai.atlassian.net/browse/FA-244)
[Adding the css modules for the pages and using page containers to fix the text]
> FA-244 Reposition the place holder texts in the premium features and reports sub sections

- frontend/src/components/Navbar/NavBar.tsx
- frontend/src/components/ProfilePanel/Profile.module.css
- frontend/src/components/ProfilePanel/Profile.tsx
[FA-215](https://salesfactoryai.atlassian.net/browse/FA-215)
[Just changing the profile dropdown to be a Modal]
> FA-215 refactor Display Navbar Items as Modals on Mobile

- backend/app.py
Reverts Salesfactory/gpt-rag-frontend#197
> Revert "FA-218 Implement Financial email user flow"

- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/FeedbackRating/FeedbackRating.module.css
- frontend/src/components/FeedbackRating/FeedbackRating.tsx
- frontend/src/components/QuestionInput/QuestionInput.module.css
- frontend/src/components/Sidebar/Sidebar.module.css
- frontend/src/components/StartNewChatButton/StartNewChatButton.module.css
- frontend/src/components/StartNewChatButton/StartNewChatButton.tsx
- frontend/src/pages/chat/Chat.module.css
[FA-264](https://salesfactoryai.atlassian.net/browse/FA-264)
[Changing the chat disclaimer position for mobile devices, the Feedback text color and position, created a new hover for the start a new chat button, fixed cursor behavior with the premium features, and changed the chat answer text size]
> FA-264 Improve UI style and behavior

- frontend/src/pages/chat/Chat.module.css
[FA-112](https://salesfactoryai.atlassian.net/browse/FA-112)
[Change the Disclaimer in mobile devices]
> FA-112 refactor Adding CSS styles to make the text responsive

- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/HistoryPannel/ChatHistoryPannel.module.css
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/UserChatMessage/UserChatMessage.module.css
- frontend/src/pages/layout/_Layout.module.css
[FA-266](https://salesfactoryai.atlassian.net/browse/FA-266)
[The ticket mentioned the arrangements that were made to the UI]
> FA-266 Sidebar, History and Chat style improvements

- frontend/src/api/models.ts
- frontend/src/components/HistoryPannel/ChatHistoryListItem.tsx
- frontend/src/providers/AppProviders.tsx
Reverts Salesfactory/gpt-rag-frontend#203
> Revert "Filter conversations"

- frontend/src/api/models.ts
- frontend/src/components/HistoryPannel/ChatHistoryListItem.tsx
- frontend/src/providers/AppProviders.tsx
Reverts Salesfactory/gpt-rag-frontend#204
> Revert "Revert "Filter conversations""

- frontend/src/api/models.ts
- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/HistoryPannel/ChatHistoryListItem.tsx
- frontend/src/components/HistoryPannel/ChatHistoryPannel.module.css
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/UserChatMessage/UserChatMessage.module.css
- frontend/src/pages/layout/_Layout.module.css
- frontend/src/providers/AppProviders.tsx
> Release 0.1.2

- frontend/src/components/FinancialAssistantPopup/FinancialAssistantPopup.module.css
- frontend/src/components/FinancialAssistantPopup/FinancialAssistantPopup.tsx
- frontend/src/pages/chat/Chat.tsx
[FA-272](https://salesfactoryai.atlassian.net/browse/FA-270)
[Adding a pop-up modal that disappears after 1.5 seconds, notifying the user that the Financial Assistant mode has been activated or deactivated]
> FA-272 Create the Financial Assistant activation pop-up

- frontend/src/components/HistoryPannel/ChatHistoryPanel.tsx
- frontend/src/components/SettingsPanel/index.tsx
- frontend/src/pages/layout/_Layout.module.css
[FA-273](https://salesfactoryai.atlassian.net/browse/FA-273)
[When a user clicks outside of these modals they will automatically close and fix chat size]
> FA-273 Fix Modals Settings, Chat History and fix the chat size

- frontend/src/pages/chat/Chat.tsx
[FA-270](https://salesfactoryai.atlassian.net/browse/FA-270)
[Added the welcome page to change dynamically when the user selects the Financial Assistant option ]
> Fa 270 Create Financial Agent Welcome Page

- frontend/src/api/api.ts
- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/Answer/Answer.tsx
- frontend/src/components/HistoryPannel/ChatHistoryPanel.tsx
- frontend/src/components/SettingsPanel/index.tsx
- frontend/src/pages/layout/_Layout.module.css
[FA-247](https://salesfactoryai.atlassian.net/browse/FA-247)
[When you click on the links in an answer, it opens in another window.]
> FA-247 html links in sources for hd test are returning a page not found error

- frontend/src/components/FeedbackRating/FeedbackRating.module.css
- frontend/src/components/FeedbackRating/FeedbackRating.tsx
[FA-278](https://salesfactoryai.atlassian.net/browse/FA-278)
[Feedback rating modal responsiveness and dropdown was fixed]
> FA-278 Fix Feedback Rating modal responsiveness and Dropdown

- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/pages/financialassistant/FinancialAssistant.module.css
- frontend/src/pages/financialassistant/FinancialAssistant.tsx
[FA-164](https://salesfactoryai.atlassian.net/browse/FA-164)
[Add financial assistant section in Admin Features]
> FA-164 Update the user interface (UI) to include an option that allows users to subscribe to the financial assistant feature.

- backend/requirements.txt
- backend/shared/cosmo_db.py
[FA-282](https://salesfactoryai.atlassian.net/browse/FA-282)
[Configure Cosmos DB for data storage and connection, some functions were created in the cosmo_db.py file to test that it could safely connect to the db, which will be useful when you need to do a CRUD of the data]
> FA- 282 Set Up Cosmos DB for Data Storage and Connection

- backend/app.py
- backend/app_config.py
- backend/financial_doc_processor.py
- backend/requirements.txt
- backend/utils.py
[PROJ-289](https://salesfactoryai.atlassian.net/browse/FA-289)
Implemented an endpoint to retrieve financial statements from SEC EDGAR, convert them to PDF format, and upload the resulting files to Azure Blob Storage.
payload format: 
{
"equity_ids": ["MS", "HD"],
"filing_types": ["10-K", "10-Q"] <--- this is optional
}
> FA-289 added endpoint for financial ingestion

- backend/app.py
- backend/shared/cosmo_db.py
- frontend/src/api/api.ts
[FA-283](https://salesfactoryai.atlassian.net/browse/FA-283)
[Creation of CRUD for the resource container, as well as a function in api.ts to obtain the reports depending on their type]
> FA-283 Build API Endpoints for CRUD Operations on Reports and Sources

- backend/app.py
- backend/tavily_tool.py
Allow users to filter date in search result by adding "days" parameter in TavilySearch
> add filter date range in the payload

- backend/app.py
- backend/shared/cosmo_db.py
- frontend/src/api/api.ts
[FA-306](https://salesfactoryai.atlassian.net/browse/FA-306)
[Update Cosmos DB Container and Implement POST Endpoint for curation and compannySumarization Reports]
> FA-306 update cosmos db container and implement post endpoint for curation and companny sumarization reports

- frontend/src/App.tsx
- frontend/src/api/api.ts
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/pages/reports/CurationReports.module.css
- frontend/src/pages/reports/CurationReports.tsx
- frontend/src/pages/reports/ReportCreation/CurationCreation.module.css
- frontend/src/pages/reports/ReportCreation/CurationCreation.tsx
[FA-280](https://salesfactoryai.atlassian.net/browse/FA-280)
[Page for the Creation of Curation Reports]
> Fa 280 build UI for create curation report

- frontend/src/App.tsx
- frontend/src/pages/reports/ReportCreation/SummarizationCreation.module.css
- frontend/src/pages/reports/ReportCreation/SummarizationCreation.tsx
- frontend/src/pages/reports/SummarizationReports.module.css
- frontend/src/pages/reports/SummarizationReports.tsx
- frontend/vite.config.ts
[FA-313](https://salesfactoryai.atlassian.net/browse/FA-313)
[Creating the Summarization Reports page and adding a few paths to the vite config file]
> FA-313 Create Summarization Reports page

- backend/app.py
- backend/financial_doc_processor.py
converted timezone to UTC and changed error status for process-and-summarize endpoint
> convert time zone to utc

- .env.template
- backend/app.py
- backend/financial_doc_processor.py
- backend/utils.py
[FA-321](https://salesfactoryai.atlassian.net/browse/FA-321)
Add new endpoint /api/reports/email for sending HTML emails with attachments
- Implement robust input validation for email requests
- Add secure file path handling for attachments
- Configure SMTP settings via environment variables
- Add error handling and logging for email operations
- Support multiple recipients and HTML content
Environment updates:
- Add SMTP server configuration
- Add email credentials configuration
Example Usage:
{
"subject": "test email",
"html_content": "<p>This is a test email</p>",
"recipients": ["namtran6701@gmail.com", "nam3864779@gmail.com"],
"attachment_path": "C:/SF_Repo/gpt-rag-frontend/backend/email_html_content.html"
}
Result:
{
"message": "Email sent successfully",
"status": "success"
}
> Fa 321 email distribution endpoint

- backend/app.py
- backend/shared/cosmo_db.py
- backend/utils.py
- frontend/src/api/api.ts
- frontend/src/api/models.ts
Reverts Salesfactory/gpt-rag-frontend#235
> Revert "FA-312 implement api for adding and removing summarization reports"

- frontend/src/App.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/components/Sidebar/SidebarItemTypes.ts
- frontend/src/pages/admin/Admin.tsx
- frontend/src/router/ProtectedRoute.tsx
[FA-327](https://salesfactoryai.atlassian.net/browse/FA-327)
[Configure the new role for the "platformAdmin"]
> FA-327 Set Up Role Based Access Controls for Admin Settings

- backend/app.py
- backend/financial_doc_processor.py
[FA-348](https://salesfactoryai.atlassian.net/jira/software/projects/FA/issues/FA-348?jql=project%20%3D%20%22FA%22%20ORDER%20BY%20created%20DESC)
endpoint to return blob list with additional metadata 
Example payload: 
```bash 
{
"container_name": "documents",
"prefix": "Reports/Curation_Reports",
"include_metadata": "yes",
"max_results": 10
}
```
Result: 
```bash 
{
"count": 6,
"data": [
{
"content_type": "text/html",
"created_on": "2024-12-22T22:31:44+00:00",
"last_modified": "2024-12-23T16:38:28+00:00",
"name": "Reports/Curation_Reports/Ecommerce/December_2024.html",
"size": 19008,
"url": "https://strag0vm2b2htvuuclm.blob.core.windows.net/documents/Reports/Curation_Reports/Ecommerce/December_2024.html"
},
{
"content_type": "text/html",
"created_on": "2025-01-08T02:42:58+00:00", …
```
> Fa 348 endpoint to list all files from a container

- backend/app.py
- backend/shared/cosmo_db.py
[FA-336](https://salesfactoryai.atlassian.net/browse/FA-336)
[Security has been added to endpoints and fix bug with date]
> FA-336 Strengthening endpoint security

- backend/app.py
- backend/app_config.py
- backend/financial_doc_processor.py
- backend/llm_config.py
> FA 349 get secrets and rename environments vars

- backend/app.py
- frontend/src/App.tsx
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/pages/reports/ReportCreation/ReportTemplateCreation.module.css
- frontend/src/pages/reports/ReportCreation/ReportTemplateCreation.tsx
- frontend/src/pages/reports/ReportTemplates.module.css
- frontend/src/pages/reports/ReportTemplates.tsx
[FA-311](https://salesfactoryai.atlassian.net/browse/FA-311)
Refactor part of the backend to meet the requirements (CompanyTicker, CompanyName).
Create page/report templates 
Create delete function for page /report-templates 
Create /create-template-report to create templates
Create a new pop workflow using state
> FA-311 implement UI for managing templates summarization reports

- frontend/src/App.tsx
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
- frontend/src/providers/AppProviders.tsx
[FA-344](https://salesfactoryai.atlassian.net/browse/FA-344)
[Creating the UI for the subscription management page]
> FA-344 Create the subscription management page UI

- frontend/src/App.tsx
- frontend/src/api/api.ts
- frontend/src/components/Sidebar/Sidebar.tsx
- frontend/src/pages/reports/Reports.tsx
> FA-329 manage and download organization reports

- backend/app.py
- frontend/src/api/api.ts
[FA-338](https://salesfactoryai.atlassian.net/browse/FA-338)
[Change or delete the webapp subscription plan, endpoints and functions in api.ts]
> FA-338 Create the endpoints and functions to cancel a subscription and change a subscription

- backend/rp2email.py
> Update rp2email function

- frontend/src/pages/reports/DistributionLists.module.css
- frontend/src/pages/reports/DistributionLists.tsx
- frontend/src/pages/reports/ReportCreation/CurationCreation.module.css
- frontend/src/pages/reports/ReportCreation/CurationCreation.tsx
[FA-280](https://salesfactoryai.atlassian.net/browse/FA-280)
[This PR addresses some of the issues presented in the comments of that task. Mostly on the Curation Reports page and the
Distribution Lists page]
> Hotfix-FA-280 Minor fixes in Distribution Lists for the PlatformAdmin role and fixes in the CurationCreation page

- frontend/src/App.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-345](https://salesfactoryai.atlassian.net/browse/FA-345)
[Implementing the subscription change in the UI]
> FA-345 Integrate subscription management page with backend API

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-373](https://salesfactoryai.atlassian.net/browse/FA-373)
[Adding endpoints to implement the Stripe Customer Portal]
> FA-373 Implement the stripe customer portal to cancel and change payment information of the actual subscription

- backend/app.py
- backend/curation_report_generator.py
- backend/financial_agent_utils/curation_report_config.py
- backend/financial_agent_utils/curation_report_utils.py
- backend/financial_doc_processor.py
- backend/prompts/curation_reports/company_analysis.py
- backend/prompts/curation_reports/ecommerce.py
- backend/prompts/curation_reports/home_improvement.py
- backend/prompts/curation_reports/monthly_economics.py
- backend/prompts/curation_reports/weekly_economics.py
In order to generate company analysis report, users need to include **company_name** in the body request
> Company analysis and home improvement report 

- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-344](https://salesfactoryai.atlassian.net/browse/FA-344)
[Minor changes and stylizing the Subscription Change modal]
> HOTFIX-FA-344 Create the Subscription Change Page UI

- backend/app.py
- backend/shared/cosmo_db.py
- frontend/src/api/api.ts
- frontend/src/pages/admin/Admin.module.css
- frontend/src/pages/admin/Admin.tsx
[FA-200](https://salesfactoryai.atlassian.net/browse/FA-200)
[Creation of the edit user endpoint and UI functionality]
> FA-200 BE-Create/Verify endpoints to edit user

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/components/PaymentGateway/PaymentGateway.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-384](https://salesfactoryai.atlassian.net/browse/FA-384)
[Add missing things to create the log in the "auditLogs" container]
> FA 384 Implement Audit Logging FE

- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-344](https://salesfactoryai.atlassian.net/browse/FA-344)
[Addressing the new comments. Small changes]
> HOTFIX FA 344 Create the subscription management page UI

- frontend/src/components/QuestionInput/QuestionInput.module.css
- frontend/src/pages/chat/Chat.module.css
[FA-362](https://salesfactoryai.atlassian.net/browse/FA-362)
[Removing padding from the chatbox]
> FA-362 Remove Padding from the chatbox

- frontend/src/pages/chat/Chat.module.css
- frontend/src/pages/chat/Chat.tsx
[FA-363](https://salesfactoryai.atlassian.net/browse/FA-363)
[Changing the size of the chat boxes to take more screen space. Minor fixes]
> FA-363 Resize the chat boxes

- frontend/src/api/api.ts
[FA-200](https://salesfactoryai.atlassian.net/browse/FA-200)
[Minor fix. Fixing the route to properly edit the user in the UI]
> HOTFIX-FA-200 BE Create/Verify Endpoints to edit user

- frontend/cypress/e2e/dashboard.cy.ts
> FA CYPRESS provide a default WEB_APP_URL value as a fallback

- frontend/cypress/e2e/dashboard.cy.ts
> FA cypress log WEB_APP_URL

- frontend/cypress/e2e/dashboard.cy.ts
> Fa set local url as constant

- frontend/cypress/e2e/dashboard.cy.ts
> FA-CYPRESS hardcode URL on test run

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-388](https://salesfactoryai.atlassian.net/browse/FA-388)
[Fixed the bug with the Customer Portal]
> FA-388 Customer Portal Triggers Unintended Financial Assistant Subscription Changes

- backend/app.py
- backend/rp2email.py
[FA-249](https://salesfactoryai.atlassian.net/browse/FA-249?atlOrigin=eyJpIjoiMWExNzEyY2FiMjYyNGQ0MDhjODE2NjJjMzJkMWZiOGIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
change report name's attachment and fix storage path for company analysis
> Modify report name and email content

- frontend/src/pages/admin/Admin.module.css
- frontend/src/pages/admin/Admin.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagement.tsx
[FA-200](https://salesfactoryai.atlassian.net/browse/FA-200)
[Fixing the issue where if a user is edited twice, the table won't reload. Also fixing that issue in subscriptionmanagement page and fixing the background for the platformUser role]
> FA-200 Create/Verify endpoints to edit user UI Fix

- frontend/src/components/FinancialAssistantPopup/FinancialAssistantPopup.module.css
- frontend/src/pages/reports/DistributionLists.module.css
[FA-401](https://salesfactoryai.atlassian.net/browse/FA-401)
[Small fix. Fixing the background issue and the position of the Financial Assistant Toggle]
> FA-401 Distribution List background issue

- backend/app.py
- backend/utils.py
[FA-396](https://salesfactoryai.atlassian.net/browse/FA-396)
[Replacing the api/settings with local implmentation]
> FA-396 Remove endpoint orchestrator call to endpoint api settings and replace with local implementation

- backend/app.py
- backend/shared/cosmo_db.py
[FA-397](https://salesfactoryai.atlassian.net/browse/FA-397)
add the cosmosdb logic to create_organization into the app.py and backend
use the custom function create_error_response() to create responses
raise custom execptions to manage errors
> Fa 397 refactor create organization

- backend/app.py
- backend/shared/cosmo_db.py
[FA-397](https://salesfactoryai.atlassian.net/browse/FA-397)
add the cosmosdb logic to checkuser into the app.py and backend 
use the custom function create_error_response() to create responses
raise custom execptions to manage errors
> Fa 397 refactor checkuser endpoint

- backend/app.py
- backend/shared/cosmo_db.py
[FA-397](https://salesfactoryai.atlassian.net/browse/FA-397)
iterate the logic from orchestrator to app.py
> Fa 397 refactor create invitation endpoint

- backend/app.py
- backend/utils.py
- frontend/src/api/api.ts
[FA-396](https://salesfactoryai.atlassian.net/browse/FA-396)
[Replacing the api/getusers with local implementation. This PR also tackles the api/deleteuser and /api/auth/user (FA-395) because the auth users uses the get_user function.]
> FA-396 Remove endpoint orchestrator call to endpoint api getuser and replace with local implementation

- backend/app.py
- backend/utils.py
- frontend/src/providers/AppProviders.tsx
[FA-395](https://salesfactoryai.atlassian.net/browse/FA-395)
[Applied what was specified in the task for the chat history endpoint]
> FA 395 - Remove endpoint orchestrator call to endpoint /api/chat-history and replaced with local implementation

- backend/app.py
- backend/shared/cosmo_db.py
- backend/utils.py
[FA-396](https://salesfactoryai.atlassian.net/browse/FA-396)
[Replacing the api/invitations with local implmentation]
> FA-396 Remove endpoint orchestrator call to endpoint api invitations and replace with local implementation

- backend/app.py
- backend/utils.py
[FA-396](https://salesfactoryai.atlassian.net/browse/FA-396)
[Replacing the api/feedback with local implmentation]
> FA-396 Remove endpoint orchestrator call to endpoint api feedback and replace with local implementation

- backend/app.py
- backend/shared/cosmo_db.py
- backend/utils.py
> Fix Conflict merge errors

- frontend/vite.config.ts
> Add path and util aliases for browser compatibility in Vite config

- backend/app.py
- frontend/src/components/Answer/Answer.tsx
- frontend/src/pages/chat/Chat.tsx
Reverts Salesfactory/gpt-rag-frontend#309
> Revert "Add streaming support for ChatGPT responses and improve loading text …"

- backend/app.py
- frontend/src/components/Answer/Answer.tsx
- frontend/src/pages/chat/Chat.tsx
[FA-421] https://salesfactoryai.atlassian.net/browse/FA-421
Change Structure to handle streamed response, NEEDS refactor-graph-agent branch in the orchestrator to be MERGED FIRST.
Change endpoint to stream the response instead of using request response approach.
> Fa 421 modify frontend to enable streaming

- frontend/src/pages/chat/Chat.tsx
> Add user authentication headers to ChatGPT streaming request

- frontend/src/pages/chat/Chat.tsx
[PROJ-432][(link-to-ticket)](https://salesfactoryai.atlassian.net/browse/FA-432?atlOrigin=eyJpIjoiNmYyMzQ2Y2EzMzQwNGVjN2IyMTY4MTBjNjQ4MTdlYzYiLCJwIjoiaiJ9)
> Remove source URL artifacts from chat response

- frontend/src/pages/chat/Chat.tsx
[PROJ-433](link-to-ticket)https://salesfactoryai.atlassian.net/browse/FA-433?atlOrigin=eyJpIjoiYTU5YWE2MzJmZGQ3NDJhMDlhNTM0ZGYzMTNkMDY4MDkiLCJwIjoiaiJ9
> Implement restart chat functionality with ref-based control

- frontend/src/pages/chat/Chat.tsx
> Add conditional API request method based on financial assistant mode

- backend/app.py
- backend/shared/cosmo_db.py
- frontend/src/api/api.ts
- frontend/src/pages/reports/ReportCreation/ReportTemplateCreation.tsx
- frontend/vite.config.ts
[FA-398](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-398)
Get the companies from cosmosDB and use it in the frontend report creation
> 398 use the company data in the freedaid UI

- backend/app.py
- backend/rp2email.py
- backend/utils.py
https://salesfactoryai.atlassian.net/browse/FA-435
> FA-435 format reports and generate email

- backend/app.py
- backend/rp2email.py
- backend/summarization.py
> FA-461 modify flow to save formatted docs in blob

- backend/app.py
- backend/financial_doc_processor.py
- backend/rp2email.py
[FA-465](https://salesfactoryai.atlassian.net/browse/FA-465)
Helped by @PedroLabrador 💪🏼 
> Fa 465 add metadata blob

- backend/app.py
- Modify file path generation for reports and summaries to include company name and current date
- Improve file naming consistency across different report types
- Remove redundant logging statements
[FA-473](https://salesfactoryai.atlassian.net/browse/FA-472)
> FA-465 Update report and summary file naming convention

- backend/app.py
- backend/financial_agent_utils/curation_report_tools/web_search.py
[FA-497](https://salesfactoryai.atlassian.net/jira/software/projects/FA/issues/FA-497?jql=project%20%3D%20%22FA%22%20ORDER%20BY%20created%20DESC)
1. sync font for email and report 
2. replace web app url with INVITATION_LINK env (@PedroLabrador @Alexjes98 you know what I mean :) )
> Fa 497 sync font for report and email

- backend/app.py
- backend/llm_config.py
- backend/prompts/summarization_reports/layout_template.py
- backend/summarization.py
[FA-499](https://salesfactoryai.atlassian.net/jira/software/projects/FA/issues/FA-499?jql=project%20%3D%20%22FA%22%20ORDER%20BY%20created%20DESC)
- Improve the summarization report for clarity and accuracy.  
- Implement a layout template to ensure consistency across all company reports.  
- Adjust the final summary function to format the output directly, eliminating the need for the last API call, which is solely for formatting.
> Fa 499 improve format of the summarized report

- backend/financial_doc_processor.py
- backend/report_email_templates/email_templates.py
- backend/report_email_templates/html/report_email.html
- backend/rp2email.py
* Update download_blob_from_a_link method to remove return type hint.
* Add document_id to email data for improved context in report emails.
* Modify email template to include follow-up URL with document ID.
* Update HTML template to use dynamic follow-up URL instead of static link.
[FA-466](https://salesfactoryai.atlassian.net/browse/FA-466)
> FA-466 Enhance email template and blob download functionality

- backend/curation_report_generator.py
- backend/llm_config.py
- backend/prompts/curation_reports/company_analysis.py
- backend/prompts/curation_reports/ecommerce.py
- backend/prompts/curation_reports/home_improvement.py
- backend/prompts/curation_reports/monthly_economics.py
- backend/prompts/curation_reports/weekly_economics.py
- backend/requirements.txt
[FA-503](https://salesfactoryai.atlassian.net/browse/FA-503)
- Generate report with o1
- Enable options to generate report with Deepseek models 
- fine tuned prompts
> Fa 503 generate report with r1 and o1

- frontend/src/components/DocView/FileViewer.tsx
- frontend/src/components/DocView/HTMLViewer.tsx
- frontend/src/pages/chat/Chat.tsx
- frontend/src/utils/functions.ts
[FA-516](https://salesfactoryai.atlassian.net/browse/FA-516?focusedCommentId=11000)
Enable HTML citation preview
> support html preview for internal documents

- backend/app.py
- backend/curation_report_generator.py
- backend/financial_agent_utils/curation_report_tools/web_search.py
- backend/financial_doc_processor.py
- backend/llm_config.py
- backend/prompts/curation_reports/company_analysis.py
- backend/prompts/curation_reports/ecommerce.py
- backend/prompts/curation_reports/home_improvement.py
- backend/prompts/curation_reports/monthly_economics.py
- backend/prompts/curation_reports/weekly_economics.py
- backend/prompts/summarization_reports/layout_template.py
- backend/requirements.txt
- backend/rp2email.py
- backend/shared/cosmo_db.py
- backend/summarization.py
- backend/utils.py
- frontend/src/api/api.ts
- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/UserChatMessage/UserChatMessage.module.css
- frontend/src/index.css
- frontend/src/pages/chat/Chat.tsx
- frontend/src/pages/reports/ReportCreation/ReportTemplateCreation.tsx
- frontend/vite.config.ts
> Release 1.0.4

- backend/financial_doc_processor.py
[FA-523](https://salesfactoryai.atlassian.net/jira/software/projects/FA/issues/FA-523?jql=project%20%3D%20%22FA%22%20ORDER%20BY%20created%20DESC)
revert %20 back to space so the file names could be located in the storage
> Fa 523 fix blob links containing space

- backend/app.py
use black logo for curation reports
> use black logo for report

- backend/app.py
- backend/financial_doc_processor.py
> Release 1.0.7

- backend/shared/cosmo_db.py
- backend/utils.py
[FA-543](https://salesfactoryai.atlassian.net/browse/FA-543)
Fixed problem with emails being case sensitive when creating the user
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```
If applicable, provide a link to the relevant backlog item or issue.
If deploying this change could impact existing applications, please specify.
```
[ ] Yes
[ ] No
```
If this change depends on pull requests in other repositories within the solution, provide the links below.
If the changes add new functionality, update the documentation accordingly.
```
[ ] Yes
[ ] No
```
If this change adds a new functionality, provide a link to its documentation.
See …
> FA-543 Invited users are incorrectly redirected to subscription tier selection after account creation

- backend/app.py
- backend/shared/cosmo_db.py
[FA-548](https://salesfactoryai.atlassian.net/browse/FA-548)
[A refactoring was performed to obtain the organizations in which a user is using the invitations container.]
> HOTFIX-FA-548-add-get-organizations-endpoint

- frontend/src/components/OrganizationSelector/OrganizationSelectorPopup.module.css
- frontend/src/components/OrganizationSelector/OrganizationSelectorPopup.tsx
[FA-546](https://salesfactoryai.atlassian.net/browse/FA-546)
[I created the UI menu to let the users select the organization they wanna use]
> FA-546 Menu UI for select organization

- backend/shared/cosmo_db.py
- backend/utils.py
[FA-549](https://salesfactoryai.atlassian.net/browse/FA-549)
[FA-550](https://salesfactoryai.atlassian.net/browse/FA-550)
[FA-549 Add the new parameter to the Invitations container
FA-550 Implement the logic to add the parameter if a user is invited and accepts the invitation.]
> FA-550 Update invitation record with user id upon acceptance

- backend/app.py
- backend/utils.py
[FA-551](https://salesfactoryai.atlassian.net/browse/FA-551)
Refactoring the deleteuser util and fixing a bug with the frontend, and refactoring the getuser function to take the users based on the invited_user_id field.
Merge only when all the user invitations have the invited_user_id field on the database
> FA-551 Refactor deleteuser to set active field to false

- backend/shared/cosmo_db.py
- frontend/cypress/e2e/dashboard.cy.ts
- frontend/src/api/api.ts
- frontend/src/components/OrganizationSelector/OrganizationSelectorPopup.tsx
- frontend/src/pages/onboarding/Onboarding.tsx
- frontend/src/providers/AppProviders.tsx
- frontend/src/router/ProtectedRoute.tsx
[FA-547](https://salesfactoryai.atlassian.net/browse/FA-547)
[This is the logic to be able to get and load the multi-organizations, we need to change that prompt for the created UI and apply the changes in the containers to avoid errors.
All the invitations were created with the additional parameter in the Db, we can now merge.]
> FA 547 review user flow for organization selection

- frontend/src/components/Answer/Answer.module.css
enhance "Generating response" animation to improve user experience
> Add-fade-in-out-for-"Generating-response"

- backend/app.py
- backend/shared/cosmo_db.py
- backend/utils.py
- frontend/src/api/api.ts
- frontend/src/components/OrganizationSelector/OrganizationSelectorPopup.module.css
- frontend/src/components/OrganizationSelector/OrganizationSelectorPopup.tsx
- frontend/src/pages/admin/Admin.tsx
- frontend/src/pages/logout/Logout.tsx
- frontend/vite.config.ts
[FA-553](https://salesfactoryai.atlassian.net/browse/FA-553)
[* A change was made to the email template to add the name of the inviting organization.
* New path added to vite.config.ts
* Modified the inviteUser to include the organizationName parameter.
* Updated the logout button to delete the localstorage of the application when the user logs out.
* Refactored the code of get_users to filter correctly without consuming a lot of resources]
> FA-553 Onboarding: Show Organization Name During Invitation and Signup

- frontend/src/pages/organization/Organization.tsx
- frontend/src/providers/AppProviders.tsx
display organization id description in the org setting
> Display-organization-description-in-the-UI-organization-setting

- backend/app.py
- backend/utils.py
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/components/SettingsPanel/index.tsx
save model selection from the front end to user setting in cosmos
> Enable-model-selection-for-user-settings

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/pages/chat/Chat.tsx
[FA-558](https://salesfactoryai.atlassian.net/browse/FA-558)
[This change was made so that the orchestrator takes the organization in which the user is logged in when asking questions to the agent.]
> FA-558 refactor logic to retrieve user organization via invitations container front

- backend/app.py
- backend/shared/cosmo_db.py
[FA-568](https://salesfactoryai.atlassian.net/browse/FA-568)
[Create the endpoint to update the organization with the new parameters]
> FA-568 update endpoint to support new fields

- frontend/src/pages/organization/Organization.module.css
- frontend/src/pages/organization/Organization.tsx
- frontend/src/providers/AppProviders.tsx
[FA-566](https://salesfactoryai.atlassian.net/browse/FA-566)
[* Update the UI and the data model of the organizations page.]
> FA-566 Update Organization Page UI

- frontend/src/api/api.ts
- frontend/src/pages/organization/Organization.tsx
[FA-569](https://salesfactoryai.atlassian.net/browse/FA-569)
[* integrate the UI with the backend]
> FA-569 connect frontend to backend for managing new organization fields

- frontend/src/components/AnalysisPanel/AnalysisPanel.tsx
- frontend/src/pages/chat/Chat.tsx
> Release 1.0.12

- frontend/src/pages/admin/Admin.tsx
[FA-587](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-587)
> FA-587 Sanitize email input in CreateUserForm by converting to lowercase

- backend/app.py
- backend/shared/cosmo_db.py
[FA-593](https://salesfactoryai.atlassian.net/browse/FA-593)
[An invitation verification was implemented with the invitation_link so that when the user clicks on the email with the invitation link, it activates the invitation and redirects the user to login securely to continue with the account creation or login process.]
> FA-593 Confirm user invitation via invitation link

- backend/app.py
- backend/shared/cosmo_db.py
- frontend/cypress/e2e/dashboard.cy.ts
- frontend/src/api/api.ts
- frontend/src/providers/AppProviders.tsx
- frontend/vite.config.ts
[FA-595](https://salesfactoryai.atlassian.net/browse/FA-595)
[* Fix bug with the user role from invitations]
> FA-595 User Role Is Taken from users Container Instead of Invitation

- frontend/src/pages/organization/Organization.tsx
update app context after changes have been saved
> FA-585-fix-bug-regarding-saving-changes-to-org-desc

- frontend/src/App.tsx
[FA-590](https://salesfactoryai.atlassian.net/browse/FA-590?focusedCommentId=11348&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-11348)
> Add logout route to App component unprotected routes

- frontend/src/App.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
[Create a secondary path to view the changes in the new UI]
> Create Route to view changes new UI

- frontend/src/components/Navbar/NavBarcopy.tsx
> HOTFIX route

- backend/app.py
- backend/shared/cosmo_db.py
- frontend/src/App.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/Organizationcopy.module.css
- frontend/src/pages/organization/Organizationcopy.tsx
- frontend/src/providers/AppProviders.tsx
[FA-581](https://salesfactoryai.atlassian.net/browse/FA-581)
> FA- 581 workspace governance page redesign

- frontend/src/App.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
- frontend/src/pages/admin/Admincopy.module.css
- frontend/src/pages/admin/Admincopy.tsx
- frontend/src/pages/layout/_Layoutcopy.module.css
[FA-579](https://salesfactoryai.atlassian.net/browse/FA-579)
[* Redesign Team Management page]
> FA-579 team management page redesign

- frontend/src/App.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
[FA-583](https://salesfactoryai.atlassian.net/browse/FA-583)
[Adding the copy of the page]
> Fa 583 subscription plan page redesign

- backend/app.py
- backend/shared/cosmo_db.py
- backend/utils.py
- frontend/src/components/Sidebarcopy/Sidebarcopy.module.css
- frontend/src/pages/admin/Admincopy.module.css
- frontend/src/pages/admin/Admincopy.tsx
- frontend/src/pages/organization/Organization.tsx
- frontend/src/pages/organization/Organizationcopy.tsx
- frontend/src/providers/AppProviders.tsx
[FA-579](https://salesfactoryai.atlassian.net/browse/FA-579)
[Responding to the comments of the task]
> HOTFIX FA-579 Team management page redesign

- frontend/src/App.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
- frontend/src/pages/reports/DistributionListscopy.module.css
- frontend/src/pages/reports/DistributionListscopy.tsx
[FA-596](https://salesfactoryai.atlassian.net/browse/FA-596)
[* Distribution list page redesign]
> FA-596 distribution list page redesign

- frontend/src/pages/organization/Organizationcopy.module.css
- frontend/src/pages/organization/Organizationcopy.tsx
[FA-581](https://salesfactoryai.atlassian.net/browse/FA-581)
[* Respond to comments on the site]
> HOTFIX FA-581 workspace governance page redesign

- frontend/src/App.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
- frontend/src/pages/chat/Chatcopy.module.css
- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/reports/Reportscopy.module.css
- frontend/src/pages/reports/Reportscopy.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
[FA-592](https://salesfactoryai.atlassian.net/browse/FA-592)
[Redesign UI Report Dashboard and some fixed in the subscription page and in the chat screen]
> FA-592 Report page redesign

- frontend/src/App.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
- frontend/src/index.css
- frontend/src/pages/resources/UploadResourcescopy.module.css
- frontend/src/pages/resources/UploadResourcescopy.tsx
- frontend/vite.config.ts
[FA-607](https://salesfactoryai.atlassian.net/browse/FA-607)
[Redesign of the user interface File Upload Page]
> FA 607 file upload page redesign

- frontend/src/pages/admin/Admincopy.module.css
- frontend/src/pages/admin/Admincopy.tsx
[FA-579](https://salesfactoryai.atlassian.net/browse/FA-579)
[* Address comments]
> HOTFIX-FA-579-Team-Management-Page-redesign

- frontend/src/components/ChatHistorySidebar/ChatHistorySidebar.module.css
- frontend/src/components/ChatHistorySidebar/ChatHistorySidebar.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
[FA-599](https://salesfactoryai.atlassian.net/browse/FA-599)
[* Creation of a new ChatHistorySidebar component and its implementation to the navbar.]
> FA-599 Chat History Redesign

- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
- frontend/src/components/SettingsPanel/SettingsModalcopy..module.css
- frontend/src/components/SettingsPanel/SettingsModalcopy.module.css
- frontend/src/components/SettingsPanel/indexCopy.tsx
- frontend/src/pages/chat/Chatcopy.tsx
[FA-600](https://salesfactoryai.atlassian.net/browse/FA-600)
[* Model setting modal redesign]
> FA-600 model setting modal redesign

- backend/app.py
- frontend/src/pages/admin/Admin.tsx
- frontend/src/pages/admin/Admincopy.tsx
- frontend/src/pages/reports/Reportscopy.module.css
- frontend/src/pages/resources/UploadResourcescopy.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
[FA-583](https://salesfactoryai.atlassian.net/browse/FA-583)
[FA-592](https://salesfactoryai.atlassian.net/browse/FA-592)
[ * Make arrangements on Upload Resources and Subscription Management pages, Wanjiru comments
* Create an endpoint to be able to download documents from the upload resources page.
* Fix a bug in inviting users to send email to the database without spaces]
> HOTFIX-FA-592-FA-583

- frontend/src/components/PaymentGateway/PaymentGateway.module.css
- frontend/src/components/PaymentGateway/PaymentGateway.tsx
- frontend/src/pages/onboarding/Onboarding.tsx
[FA-628](https://salesfactoryai.atlassian.net/browse/FA-628)
[* Redesign the subscription plan page]
> FA-628-redesign-the-subscription-plan-page

- frontend/src/components/SettingsPanel/indexCopy.tsx
- Adjusted the maximum temperature for "DeepSeek-V3-0324" from 1 to 1.5.
- Enhanced temperature handling to use model-specific defaults only when no saved temperature is available.
- Updated error handling to set default values when fetching settings fails.
- Modified temperature validation to ensure it adheres to the model's defined min and max values.
> Extend-deepseek-temperature-and-pull-config-from-cosmos

- frontend/src/components/SettingsPanel/indexCopy.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-652
> FA-652-fix-button-color

- backend/utils.py
- frontend/src/components/ProfileModal/ProfileModal.module.css
- frontend/src/components/ProfileModal/ProfileModal.tsx
[FA-636](https://salesfactoryai.atlassian.net/browse/FA-636)
[* Address comments]
> HOTFIX FA-636 implement new user profile modal

- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
[FA-654](https://salesfactoryai.atlassian.net/browse/FA-654)
[Add organization name next to freddaid, visual fixes on subscription page and disable feedback panel]
> FA-654 Add the organization name next to FreddAid

- backend/app.py
- backend/shared/cosmo_db.py
- backend/utils.py
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/components/Answer/Answer.tsx
- frontend/src/components/ChatHistorySidebar/ChatHistorySidebar.module.css
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
- frontend/src/components/ProfileModal/ProfileModal.module.css
- frontend/src/components/ProfileModal/ProfileModal.tsx
- frontend/src/components/ProfilePanel/Profilecopy.module.css
- frontend/src/components/ProfilePanel/Profilecopy.tsx
- frontend/src/components/SettingsPanel/index.tsx
- frontend/src/components/SettingsPanel/indexCopy.tsx
- frontend/src/components/UserChatMessage/UserChatMessage.module.css
- frontend/src/components/UserChatMessage/UserChatMessage.tsx
- frontend/src/pages/admin/Admincopy.tsx
- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/organization/Organizationcopy.module.css
- frontend/src/pages/organization/Organizationcopy.tsx
- frontend/src/pages/reports/DistributionListscopy.tsx
- frontend/src/pages/resources/UploadResourcescopy.tsx
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
- frontend/src/providers/AppProviders.tsx
Reverts Salesfactory/gpt-rag-frontend#435
> Revert "Merge main into develop"

- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/Answer/Answer.tsx
> Fix issues with the answers

- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
[FA-666](https://salesfactoryai.atlassian.net/browse/FA-666)
[* Add tooltip for platformAdmin role]
> FA-666 User Role for platform users is wrong

- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/Answer/Answer.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
> Release 1.1.9

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/components/ChatHistorySidebar/ChatHistorySidebar.module.css
- frontend/src/components/ChatHistorySidebar/ChatHistorySidebar.tsx
- frontend/src/components/Navbar/NavBarcopy.tsx
- frontend/src/components/Navbar/Navbarcopy.module.css
- frontend/src/pages/chat/Chatcopy.module.css
- frontend/src/pages/chat/Chatcopy.tsx
allow users to export conversation from chat history and main UI
> Feat--export-conversation

- frontend/src/components/OrganizationModal/OrganizationModal.module.css
- frontend/src/components/OrganizationModal/OrganizationModal.tsx
- frontend/src/components/ProfilePanel/Profilecopy.module.css
- frontend/src/components/ProfilePanel/Profilecopy.tsx
[FA-637](https://salesfactoryai.atlassian.net/browse/FA-637)
[Implement the switch organizations, along with the profile panel fixes.]
> FA-637-Switch-Organizations

- frontend/package-lock.json
- frontend/package.json
- frontend/src/components/DocView/DocxPreviewViewer.module.css
- frontend/src/components/DocView/DocxViewer.tsx
- frontend/src/pages/chat/Chatcopy.tsx
[FA-629](https://salesfactoryai.atlassian.net/browse/FA-629)
[The react-doc-viewer library does not work for our case because it is not compatible when we bring documents from a blob.
I investigated and I saw that I could apply another library that fulfills the request, its name is “docx-preview”.]
> FA-629 Optimize document preview using react doc viewer to support pd fs and docx files

- frontend/src/pages/knowledgesources/KnowledgeSources.module.css
- frontend/src/pages/knowledgesources/KnowledgeSources.tsx
> FA-676-add-page-content-to-knowledge-sources

- frontend/src/components/AnalysisPanel/AnalysisPanel.tsx
- frontend/src/components/Answer/Answer.tsx
- frontend/src/components/Answer/AnswerParser.tsx
- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/onboarding/Onboarding.tsx
[FA-627](https://salesfactoryai.atlassian.net/browse/FA-627)
[Resolved the issue with the third step in the onboarding, and also resolved an issue with the citation in the agent responses that was consuming too many resources (too many queries).]
> FA-627 Edit the workflow to skip the third page

- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
[FA-679](https://salesfactoryai.atlassian.net/browse/FA-679)
[* Visual fixes in Subscription Management popups and delete some styles that were no longer necessary from the CSS]
> FA-679 Update The Financial Assistance Subscription Change Confirmation Window

- backend/app.py
The removed log included 
- JWT Tokens (ID tokens, refresh tokens)
- User emails
- Authentication secrets
- Session cache data
- Security tokens
Needed to remove them
> Remove-logs-that-contain-sensitive-information

- backend/app.py
- Added extraction of client principal ID and name from request headers to include in the payload sent to the external scraping service.
- Updated the payload structure to include the client principal ID.
- Introduced a check for the web scraping endpoint to ensure it is set before making the request.
> FA-682-add-organization-id-to-blob's-metadata

- frontend/src/components/Navbar/NavBarcopy.tsx
[PROJ-696](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?atlOrigin=eyJwIjoiaiIsImkiOiJiMGNlY2Y2YmFjY2I0ZGZhYjI0MmUzZjExNWExMDE3NCJ9&cloudId=114639d7-c963-4cd4-a7f1-69b31caecb9f&selectedIssue=FA-696)
[When user clicks outside of the dropdown menu it will automatically close]
> FA-696 Add click outside handler to close profile dropdown

- frontend/src/pages/admin/Admincopy.module.css
[FA-693](https://salesfactoryai.atlassian.net/browse/FA-693)
[* Change the color for the platformAdmin role]
> HOTFIX FA-693 make the team management page responsive

- frontend/src/pages/admin/Admincopy.module.css
- frontend/src/pages/admin/Admincopy.tsx
[FA-685](https://salesfactoryai.atlassian.net/browse/FA-685)
Improving the styling and Prettier fixes
> FA-685 Improving the space between the controls in team management page ui

- frontend/src/pages/knowledgesources/KnowledgeSources.module.css
[FA-704(https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?atlOrigin=eyJwIjoiaiIsImkiOiJiMGNlY2Y2YmFjY2I0ZGZhYjI0MmUzZjExNWExMDE3NCJ9&cloudId=114639d7-c963-4cd4-a7f1-69b31caecb9f&selectedIssue=FA-704)
Adjusted scrollbar and spacing so that all links are in view
> FA-704-Scrollbar-Disappears-Knowledge-Source-Page

- frontend/cypress/e2e/workspace_governance.cy.ts
- frontend/cypress/fixtures/setupTestUser.ts
- frontend/tsconfig.json
[FA-721](https://salesfactoryai.atlassian.net/browse/FA-721)
[* Add tests for the workspace governance page]
> FA-721 Implement automated testing for workspace governance page

- frontend/cypress/e2e/subscription_management.cy.ts
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
[FA-723](https://salesfactoryai.atlassian.net/browse/FA-723)
Adding tests for the subscription plans page
> FA-723 Implement automateed testing for subscription plans page

- .github/workflows/cypress-test.yml
- frontend/cypress/e2e/chat.cy.ts
- frontend/cypress/e2e/dashboard.cy.ts
- frontend/cypress/fixtures/setupTestUser.ts
> Hotfix chat test

- frontend/cypress/e2e/report_dashboard.cy.ts
[FA-724](https://salesfactoryai.atlassian.net/browse/FA-724)
[* Reports Dashboard Test]
> FA-724 Implement automated testing for report dashboard page

- frontend/src/pages/admin/Admincopy.module.css
- frontend/src/pages/admin/Admincopy.tsx
[FA-739](https://salesfactoryai.atlassian.net/browse/FA-739)
[* Fix issue with edit user modal]
> FA-739 Updating a user is not preloading the information and it is not preloading the user data

- backend/app.py
- backend/utils.py
- frontend/src/api/api.ts
- frontend/src/pages/admin/Admincopy.tsx
[FA-738](https://salesfactoryai.atlassian.net/browse/FA-738)
[* Fix delete user]
> FA-738 Delete user failed

- frontend/cypress/e2e/onboarding.cy.ts
- frontend/cypress/fixtures/setupUserWithoutOrg.ts
[FA-728](https://salesfactoryai.atlassian.net/browse/FA-728)
Cypress tests for the onboarding
> FA-728 Implement automated testing for onboarding page

- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.module.css
- frontend/src/pages/subscriptionmanagement/SubscriptionManagementcopy.tsx
[FA-740](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-740)
> FA-740 improve modal interaction on subscription management page

- frontend/cypress/e2e/chat.cy.ts
- frontend/src/pages/voicecustomer/VoiceCustomer.module.css
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
[FA-753](https://salesfactoryai.atlassian.net/browse/FA-753)
[* Implement the UI for the “Voice of Customer” page.]
> FA-753 Implement the Voice of Customer UI

- backend/app.py
- frontend/src/api/api.ts
- frontend/src/pages/voicecustomer/VoiceCustomer.module.css
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
- frontend/vite.config.ts
[FA-772](https://salesfactoryai.atlassian.net/browse/FA-772)
[* All the connection frontend with the backend, the last thing missing is the implementation of the general delete endpoint.]
> FA-772 Connect the FE with BE

- .gitignore
- backend/app.py
- frontend/cypress/e2e/knowledge_sources.cy.ts
- frontend/src/api/api.ts
- frontend/src/pages/knowledgesources/KnowledgeSources.module.css
- frontend/src/pages/knowledgesources/KnowledgeSources.tsx
- frontend/src/pages/organization/Organizationcopy.tsx
- Updated the `multipage_scrape` function in `app.py` to improve handling of organization IDs and blob storage results, ensuring successful URLs are saved to the database with appropriate logging.
- Refactored the response parsing in `KnowledgeSources.tsx` to better handle scraping results and blob storage statuses, providing clearer error messages.
- Modified CSS styles in `KnowledgeSources.module.css` to improve layout and alignment of UI components, ensuring a more user-friendly interface.
> New-webscraping-tool

- backend/shared/cosmo_db.py
> HOTFIX voice of customer DELETE

- .gitignore
- backend/app.py
- backend/shared/cosmo_db.py
- frontend/cypress/e2e/knowledge_sources.cy.ts
- frontend/cypress/e2e/voice_customer.cy.ts
- frontend/cypress/fixtures/setupTestUser.ts
- frontend/src/api/api.ts
- frontend/src/pages/knowledgesources/KnowledgeSources.module.css
- frontend/src/pages/knowledgesources/KnowledgeSources.tsx
- frontend/src/pages/organization/Organizationcopy.tsx
- frontend/src/pages/voicecustomer/VoiceCustomer.module.css
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
- frontend/vite.config.ts
> Release 1.0.6

- backend/utils.py
- frontend/cypress/e2e/dashboard.cy.ts
- frontend/cypress/fixtures/setupTestUser.ts
- frontend/src/api/models.ts
- frontend/src/components/ChatHistorySidebar/ChatHistorySidebar.tsx
- frontend/src/providers/AppProviders.tsx
[FA-784](https://salesfactoryai.atlassian.net/browse/FA-784)
[* Add filter for the chat history]
> FA-784 Restrict Chat History to Conversations Belonging to the User’s Organization

- frontend/src/pages/knowledgesources/KnowledgeSources.module.css
- frontend/src/pages/knowledgesources/KnowledgeSources.tsx
[FA-795](https://salesfactoryai.atlassian.net/browse/FA-795)
Adding info message to knowledge sources
Prettier made some adjust to the files, but the real deal is in KnowledgeSources.tsx line 596 to 605 and the module.css in between line 185 and 243
> FA-795 Advanced Label and info message to knowledge source ui

- frontend/src/components/AnalysisPanel/AnalysisPanel.tsx
[FA-813](https://salesfactoryai.atlassian.net/browse/FA-813)
[* Add Nam Comments]
> HOTFIX FA-813 Polish throught process

- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/chat/streamParser.test.ts
- frontend/src/pages/chat/streamParser.ts
- Introduced logic to buffer and validate markdown images during streaming.
- Added regex patterns to detect complete and incomplete markdown images.
- Updated the result processing to handle markdown images incrementally, ensuring proper UI updates.
- Flushed any remaining buffered text after the stream ends to maintain message integrity.
[FA-829](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-829)
> FA-829 Enhance markdown image handling in chat component

- frontend/src/components/AnalysisPanel/AnalysisPanel.tsx
[FA-813](https://salesfactoryai.atlassian.net/browse/FA-813)
[* Fix thought process]
> HOTFIX FA-813 thought process

- frontend/src/components/AnalysisPanel/AnalysisPanel.tsx
> HOTFIX Thought process

- frontend/src/pages/resources/UploadResourcescopy.module.css
- frontend/src/pages/resources/UploadResourcescopy.tsx
[FA-821](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-821)
Change the UI of the Upload Resources page to make it more consistent
> FA-821 update upload resources page UI

- frontend/cypress/e2e/sidebarmenu.cy.ts
- frontend/src/components/Sidebarcopy/SidebarItemcopy.tsx
- frontend/src/components/Sidebarcopy/Sidebarcopy.tsx
[FA-765](https://salesfactoryai.atlassian.net/browse/FA-765)
Adding a highlight for the active section in the sidebar
> FA-765 Highlight active section in sidebar menu

- backend/data_summary/summarize.py
- backend/tests/test_upload_sources.py
Hotfix
FA Fix Sanitizer and Add prompt instructions to skip non-ASCII characters
> FA Fix Sanitizer and Add prompt instructions to skip non-ASCII characters

- backend/app.py
- frontend/src/api/api.ts
[FA-843](https://salesfactoryai.atlassian.net/browse/FA-843)
Implementing the endpoint for create a report metadata by name
> FA-843 Implement Post Reports to store report metadata

- frontend/src/components/Navbar/NavBarcopy.tsx
[FA-852](https://salesfactoryai.atlassian.net/browse/FA-852)
Ensuring the conversations are always being fetched in the chat history
> FA-852 Missing Conversations in Chat History

- frontend/src/pages/resources/UploadResourcescopy.tsx
[FA-861](https://salesfactoryai.atlassian.net/browse/FA-861)
Limit of 20 spreadsheet files
> FA-861 Imposing a limit of 20 spreadsheet files per organization

- frontend/src/components/Answer/Answer.module.css
- frontend/src/components/Answer/Answer.tsx
- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/chat/streamParser.ts
- Removed old loading keyframes and styles.
- Added new progress indicator styles in Answer.module.css.
- Updated Answer.tsx to display progress messages and a progress bar based on the new progressState prop.
- Enhanced Chat component to manage progress state and handle progress messages from the backend.
- Introduced utility functions in streamParser.ts to identify and extract progress messages.
> Stream-progress-from-back-to-front

- frontend/cypress/e2e/upload_resources.cy.ts
- frontend/src/pages/resources/UploadResourcescopy.module.css
- frontend/src/pages/resources/UploadResourcescopy.tsx
- frontend/src/utils/fileUtils.ts
[FA-867](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1/backlog?selectedIssue=FA-867)
[Add warning to the user if exist and excel file to upload exist]
> Fa 867 show excel sheet warning after file drop and refactor

- frontend/src/components/Answer/Answer.tsx
- frontend/src/components/DocView/FileViewer.tsx
- frontend/src/pages/chat/Chatcopy.tsx
[FA-869](https://salesfactoryai.atlassian.net/browse/FA-869)
[* Fix issue with the source endswith .html]
> FA-869 Doc Preview opens and truncates webpage when citation ends in .html

- frontend/cypress/e2e/voice_customer.cy.ts
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
- frontend/src/pages/voicecustomer/useBrands.ts
The Refactor Summary
The main change was breaking apart a large, monolithic React component (VoiceCustomer.tsx) and applying the
"Thinking in React" pattern with better state management and composition.
Key Changes Made:
1. Extracted Custom Hook: Created useBrands.ts - a custom hook that handles all brand-related data fetching,
loading states, and CRUD operations
2. Added Context Pattern: Implemented a CardContext with useCard hook to manage card state (open/close, counts)
across different card instances
3. Enhanced Card Component: Upgraded from a simple wrapper to a full-featured component with:
- Context-based state management
- Built-in count tracking
- Disabled states when limits are reached
- Proper accessibility labels
Best Practices & Software Principles Applied:
1. Single …
> FA-878 to follow the

- frontend/package-lock.json
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
fix competitors duplicate cardbody
> fix competitors duplicate cardbody

- backend/routes/voice_customer.py
- frontend/src/api/api.ts
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
[FA-891](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-891)
FA-891 add connection between UI and BE industry endpoints
> FA-891 add connection between UI and BE industry endpoints

- backend/routes/voice_customer.py
- backend/shared/cosmo_db.py
- backend/tests/test_voice_customer.py
- frontend/cypress/e2e/voice_customer.cy.ts
- frontend/cypress/fixtures/setupTestUser.ts
- frontend/package-lock.json
- frontend/src/api/api.ts
- frontend/src/pages/voicecustomer/VoiceCustomer.module.css
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
[FA-893](https://salesfactoryai.atlassian.net/browse/FA-893)
[Fix Category UI and another issues with the endpoints]
> FA-893 build categories UI component

- frontend/src/components/Answer/AnswerParser.tsx
- frontend/src/components/Answer/parseAnswerToHtml.test.ts
[FA-909](https://salesfactoryai.atlassian.net/browse/FA-909)
[* Fix Citations bug]
> FA-909 Sources appear as numbered list without links at the end of some answers

- backend/app.py
- frontend/src/pages/chat/Chatcopy.tsx
[FA-916](https://salesfactoryai.atlassian.net/browse/FA-916)
[The real problem was that conversations were being saved with UTC time, and when the next day began, the frontend filter was unable to recognize those conversations.]
> FA 916 Chat History not loading in production

- frontend/src/pages/resources/UploadResourcescopy.module.css
[FA-871](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-871)
gray background now cover all the file upload page
> FA-871: Fix gray background not covering all the file upload page

- frontend/src/pages/resources/UploadResourcescopy.module.css
[FA-872](https://salesfactoryai.atlassian.net/browse/FA-872)
[* Increase the vertical size that the table can use to make better use of space.
The acceptance criteria for the task also ask to fix the white space that appears at the bottom of the page, but that task has already been created as a bug with the name FA-871 and has already been fixed in a previous PR.]
> FA-872 Stretch File Table Dynamically to Bottom of Page

- backend/app.py
- frontend/package-lock.json
- frontend/package.json
- frontend/src/pages/chat/Chatcopy.tsx
- frontend/src/pages/resources/UploadResourcescopy.module.css
- frontend/src/pages/voicecustomer/VoiceCustomer.tsx
Key Features & Fixes:
1. FA-871: File Upload Page UI Fix - Fixed gray background
not covering the entire file upload page
2. FA-893: Categories UI Component - Enhanced categories UI
component based on Maria's feedback
3. Enhanced Feedback URL Endpoint - Added authentication
requirement to the feedback URL endpoint for better security
4. Date Fix for Conversations - Fixed an issue with how
conversation dates were being saved
5. Version Bump - Updated package version from 1.3.1 to
1.3.3
Files Modified:
- backend/app.py - Backend endpoint enhancements
- frontend/package.json & frontend/package-lock.json -
Version updates
- frontend/src/pages/chat/Chatcopy.tsx - Conversation date
fixes
-
frontend/src/pages/resources/UploadResourcescopy.module.css
- UI styling fixes
- …
> Release 1.3.3

- backend/app.py
- backend/utils.py
- frontend/src/components/SettingsPanel/indexCopy.tsx
[* Remove Deepseek as a model available for use in the UI]
> Disable deepseek as an available model

- frontend/src/components/Sidebarcopy/SidebarItemcopy.tsx
[FA-955](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-955)
Added role="button" and tabIndex={0}
> Fixed: [aria-*] attributes do not match their roles

- backend/app.py
[FA-966](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?jql=&selectedIssue=FA-966)
> feat: Add authentication to multiple API endpoints for enhanced security

- backend/.bandit
- backend/requirements.txt
[[PROJ-XXX](link-to-ticket)](https://salesfactoryai.atlassian.net/browse/FA-973)
> FA-973 Code Static Analysis

- backend/gallery/blob_utils.py
- frontend/src/api/api.ts
- frontend/src/pages/gallery/Gallery.module.css
- frontend/src/pages/gallery/Gallery.tsx
[FA-1023](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-1023)
> Fa 1023 fix pagination filters

- backend/requirements.txt
- backend/routes/voice_customer.py
- backend/schemas.py
[FA-967](https://salesfactoryai.atlassian.net/jira/software/projects/FA/boards/1?selectedIssue=FA-967)
> FA-967 add pydantic schemas in voice of customer endpoints

- backend/app.py
> Refactor setup clients before app serve

- backend/app.py
- backend/shared/clients.py
[[PROJ-XXX](link-to-ticket)](https://salesfactoryai.atlassian.net/browse/FA-971)
> FA-971-logging-exposure-verification

- .github/workflows/loading-test.yml
- backend/app.py
- backend/locustfile.py
- backend/requirements.txt
- backend/routes/decorators/auth_decorator.py
- backend/routes/financial.py
- backend/routes/invitations.py
- backend/routes/upload_source_document.py
- backend/routes/users.py
- backend/routes/voice_customer.py
- backend/schemas.py
- backend/shared/clients.py
- backend/utils.py
- frontend/cypress/e2e/chat_settings_detail_level.cy.ts
- frontend/src/api/api.ts
- frontend/src/api/models.ts
- frontend/src/components/SettingsPanel/SettingsModalcopy.module.css
- frontend/src/components/SettingsPanel/indexCopy.tsx
- frontend/src/components/UploadResources/FileHeaderList.tsx
- frontend/src/components/UploadResources/UploadResources.module.css
- frontend/src/pages/chat/Chatcopy.module.css
> Release 1.3.9

- frontend/src/components/UploadModal/UploadModal.module.css
- frontend/src/components/UploadModal/UploadModal.tsx
[[PROJ-XXX](link-to-ticket)](https://salesfactoryai.atlassian.net/browse/FA-1038)
> FA-1038 file-vault-upload-modal-doesnt-close-when-drag-and-drop-a-file
